### ISSUE TITLE
Service Not available

### ISSUE THREAD

**Issue by srich-DWP** [dwp/design-examples#8]
**_Screenshot_**

**_What problem does this design solve?_**
Messaging for users when a service is down for maintenance etc...

**_Which service are you researching this design on?_**
This could be used for all Gov services

**_How have you approached the design?_**
- have you tried anything that exists already?

**_What have you learned from research?_**
- include any iterations that didn't work.

**_Have you tested this for accessibility?_**
-  if so, what were the findings?

**_Link to code_**
- if you need help publishing your code to the design-examples repo contact Colin Oakley or Craig Abbott.

**Comment by srich-DWP** [comment]
Apply for a Budgeting Loan had some service messaging screens developed which were hosted by Akami (I think) 
I'll try and get the screens and any information on testing from the project archive and post on here

**Comment by abbott567** [comment]
There is guidance for this in the GOVUK Design System now. Do we still need to maintain our own patterns for this?

https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/

**Comment by ermlikeyeah** [comment]
I don't think so but worth flagging with the wider team.

If it does "float up" a tag to show it has "matured" to the gov system would as useful.

**Comment by chdesign** [comment]
We can probably remove tabs as well now as they're also in the design system.

Thanks
Chris

On 23 July 2018 at 11:58, Simon Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't think so but worth flagging with the wider team.

If it does "float up" a tag to show it has "matured" to the gov system would as useful.

**Comment by htmlandbacon** [comment]
Agreed to close this, as it is now part of the gov.uk design system: https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/

If there is alternative needs, we should move the conversation to https://github.com/alphagov/govuk-design-system-backlog/issues/124
